/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Lead } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    nombre: 'Alejandro Sanz',
    empresa: 'Acciona Logística',
    telefono: '+34 612 345 678',
    ubicacionEstado: 'Madrid',
    ubicacionDetalle: 'Oficina Central, Calle Alcalá',
    estatus: 'NUEVO',
    fechaIngreso: '2026-05-18T10:00:00Z',
    valorEstimado: 12500,
    rif: 'V-12345678-0',
    canalOrigen: 'Facebook Ads',
    campana: 'Campaña Primavera 2026',
    vendedor: 'Carlos Pérez',
    notas: 'Interesado en la suite completa de automatización empresarial.',
    numFactura: 'FAC-2026-001',
    fechaVenta: '2026-06-01',
    categoriaInteres: 'Logística'
  },
  {
    id: 'lead-2',
    nombre: 'Sofía Rodríguez',
    empresa: 'Inovatech S.A.S.',
    telefono: '+57 300 987 6543',
    ubicacionEstado: 'Bogotá',
    ubicacionDetalle: 'Sector Chicó',
    estatus: 'NUEVO',
    fechaIngreso: '2026-05-19T08:30:00Z',
    valorEstimado: 8900,
    rif: 'J-98765432-1',
    canalOrigen: 'LinkedIn Outreach',
    campana: 'Outbound B2B Tech',
    vendedor: 'Maria Gómez',
    notas: 'Solicitó presupuesto para consultoría ágil.',
    numFactura: '',
    fechaVenta: '',
    categoriaInteres: 'Consultoría'
  },
  {
    id: 'lead-3',
    nombre: 'Marcus Miller',
    empresa: 'Summit Holdings',
    telefono: '+1 (555) 234-5678',
    ubicacionEstado: 'Florida',
    ubicacionDetalle: 'Downtown Miami',
    estatus: 'CONTACTADO',
    fechaIngreso: '2026-05-10T14:15:00Z',
    valorEstimado: 24000,
    rif: 'US-99882211',
    canalOrigen: 'Google Search',
    campana: 'Inbound SEO CRM',
    vendedor: 'Carlos Pérez',
    notas: 'Primera llamada completada. Agenda demo para el próximo martes.',
    numFactura: '',
    fechaVenta: '',
    categoriaInteres: 'Tecnología'
  },
  {
    id: 'lead-4',
    nombre: 'Mariana Gomez',
    empresa: 'Azteca Media',
    telefono: '+52 55 4321 8765',
    ubicacionEstado: 'CDMX',
    ubicacionDetalle: 'Colonia Roma',
    estatus: 'CONTACTADO',
    fechaIngreso: '2026-05-12T11:45:00Z',
    valorEstimado: 15000,
    rif: 'MX-44332211',
    canalOrigen: 'Recomendación',
    campana: 'Referidos Corporativos',
    vendedor: 'Maria Gómez',
    notas: 'Enviada propuesta personalizada. Esperando feedback técnico.',
    numFactura: '',
    fechaVenta: '',
    categoriaInteres: 'Medios'
  },
  {
    id: 'lead-5',
    nombre: 'Felipe Vargas',
    empresa: 'Patagonia Wine Group',
    telefono: '+56 9 8765 4321',
    ubicacionEstado: 'Santiago',
    ubicacionDetalle: 'Providencia',
    estatus: 'CERRADO',
    fechaIngreso: '2026-05-05T09:00:00Z',
    valorEstimado: 35000,
    rif: 'CL-88776655',
    canalOrigen: 'Email Marketing',
    campana: 'Retailers Alimentación',
    vendedor: 'Carlos Pérez',
    notas: 'Contrato firmado. Implementación planificada para junio.',
    numFactura: 'FAC-2026-045',
    fechaVenta: '2026-05-20',
    categoriaInteres: 'Alimentación'
  },
  {
    id: 'lead-6',
    nombre: 'Elena Petrova',
    empresa: 'Siberia Software',
    telefono: '+49 176 1234567',
    ubicacionEstado: 'Baviera',
    ubicacionDetalle: 'Munich Center',
    estatus: 'CERRADO',
    fechaIngreso: '2026-05-06T16:20:00Z',
    valorEstimado: 18200,
    rif: 'DE-55443322',
    canalOrigen: 'Directo',
    campana: 'Web Corporativa',
    vendedor: 'Unassigned',
    notas: 'Venta cerrada. Pago inicial recibido.',
    numFactura: 'FAC-2026-048',
    fechaVenta: '2026-05-19',
    categoriaInteres: 'Software'
  }
];
